### ISSUE TITLE
Support pnpm package manager

### ISSUE THREAD

**Issue by vjpr** [ds300/patch-package#35]
https://github.com/pnpm/pnpm

**Comment by ds300** [comment]
Hi! Looks like patch-package wouldn't work with pnpm, unfortunately.

> pnpm uses hard links and symlinks to save one version of a module only ever once on a disk. When using npm or Yarn for example, if you have 100 projects using the same version of lodash, you will have 100 copies of lodash on disk. With pnpm, lodash will be saved in a single place on the disk and a hard link will put it into the node_modules where it should be installed.

**Comment by vjpr** [comment]
Hmm, I did not think of that.

@zkochan How could this package be used for pnpm? Can a hook patch a module?

**Comment by zkochan** [comment]
@vjpr with a pnpm hook you can install a package from a local tarball instead of the registry. The local tarball can contain the modified package. Or you could publish the fixed package with a different name, or you could install if from your fork.

**Comment by ds300** [comment]
Thanks @zkochan 

The other issue is that patch-package's core patch generation UX flow wouldn't work. That flow is:

1. Edit files inside your node_modules folder
2. run patch-package to generate a patch file based on your edits

With pnpm, editing files inside your node_modules folder will affect all other pnpm projects on your machine, which is probably not what you want.

The patch application process could be automated using the hooks, but I can't think of a way to make patch generation easy. Any ideas?

**Comment by vjpr** [comment]
> With pnpm, editing files inside your node_modules folder will affect all other pnpm projects on your machine, which is probably not what you want.

For patch creation, I think this workflow still works. When `pnpm install` is run, it detects that the global store has changed and will reinstall so there is no problem there. I do it all the time.

For patch application, though currently it would never work. It would need to use the pnpm plugin feature as @zkochan mentioned.

**Comment by ds300** [comment]
closing this issue due to inactivity

**Comment by jtyers** [comment]
I'm hitting this today. Use `pnpm` regularly and now have a pressing need to patch a dependency. Unfortunately creating a patch fails under `pnpm` with:

```
$ npx patch-package mname                                                  -INSERT- 
patch-package 6.2.0
• Creating temporary folder
• Installing mname@1.5.0 with npm
• Diffing your files with clean files
{ Error: ENOENT: no such file or directory, scandir '/tmp/tmp-4739623rx72YYljFtx/node_modules/mname'
    at Object.readdirSync (fs.js:790:3)
<snip>
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/tmp/tmp-4739623rx72YYljFtx/node_modules/mname' }
<snip>
Error: ENOENT: no such file or directory, scandir '/tmp/tmp-4739623rx72YYljFtx/node_modules/mname'
    at Object.readdirSync (fs.js:790:3)
```

Digging into the way `patch-package` does its diffing, I suspect copying a directory which is itself a symlink is causing the barf.

It'd be great to support `pnpm` - in my case, I'm happy to have a patch to a dependency affect all the versions of that package installed on the system. 

Aside/as well as `pnpm` hooks, the [https://pnpm.js.org/en/workspaces](workspaces) support might be a way of getting what we want, as it looks like packages are stored per-workspace.

**Comment by lenovouser** [comment]
I am experiencing the same problem, can this be fixed on `patch-package`'s side or does this need to be done in `pnpm`?

**Comment by diachedelic** [comment]
It seems to apply existing patches ok using `pnpm@5.2.6`, `patch-package@6.2.2` and `node@12.16.1` - not sure about generating them, but that can be done manually if necessary.

**Comment by DrSensor** [comment]
same here, `pnpx patch-package <pkg>` not working
```
patch-package 6.2.2

**ERROR** No package-lock.json, npm-shrinkwrap.json, or yarn.lock file.

You must use either npm@>=5, yarn, or npm-shrinkwrap to manage this project's
dependencies.
```

**Comment by milahu** [comment]
@DrSensor fixed in #302

**Comment by cdaringe** [comment]
`pnpm` works, just with caveats.`pnpm` users need to _manage_ how they land packages `node_modules`.

- modules in need of patch need to be top-level to be hoisted into `node_modules`. you can do this by promoting your transitive deps to 1st-class deps, right in your package.json
-  install method needs to be [clone or copy](https://pnpm.js.org/npmrc#package-import-method)

**Comment by cdaringe** [comment]
...err worked, pre `**ERROR** No package-lock.json, npm-shrinkwrap.json, or yarn.lock file.` message 😆

**Comment by fatso83** [comment]
For anyone else late to the party, @milahu did the work and you can continue with patch-package and PNPM like nothing has changed by doing:
```
pnpm remove patch-package
pnpm install @milahu/patch-package-with-pnpm-support
```

The same commands apply (the executable is still `node_modules/.bin/patch-package`)

**Comment by boldwade** [comment]
This still doesn't seem to work for me after removing and installing the @milahu package:

```
$ node_modules/.bin/patch-package react-async-hook
patch-package 6.4.9

**ERROR** No package-lock.json, npm-shrinkwrap.json, or yarn.lock file.

You must use either npm@>=5, yarn, or npm-shrinkwrap to manage this project's
dependencies.

```

**Comment by cdaringe** [comment]
I ended up writing a garbage little script to generate patches from my pnpm project's node_modules, but using `npm` and a temporary workspace to actually generate the patches.

https://gist.github.com/cdaringe/66c7cd5f95f74766f9eb1e699fdd7399

it's rough around the edges, but gets the job done. YMMV

**Comment by milahu** [comment]
> This still doesn't seem to work for me

thanks for reporting. this could be the same issue as https://github.com/milahu/patch-package-with-pnpm-support/issues/4

does `npx patch-package --debug` say more?

what does patch-package say with

```diff
--- a/node_modules/@milahu/patch-package-with-pnpm-support/dist/detectPackageManager.js
+++ b/node_modules/@milahu/patch-package-with-pnpm-support/dist/detectPackageManager.js
@@ -54,6 +54,13 @@
     const packageLockExists = fs_extra_1.default.existsSync(path_1.join(appRootPath, "package-lock.json"));
     const shrinkWrapExists = fs_extra_1.default.existsSync(path_1.join(appRootPath, "npm-shrinkwrap.json"));
     const yarnLockExists = fs_extra_1.default.existsSync(path_1.join(appRootPath, "yarn.lock"));
+console.dir({
+ packageLockExists,
+ shrinkWrapExists,
+ yarnLockExists,
+ findYarnWorkspaceRoot: find_yarn_workspace_root_1.default(),
+ isFileInPnpmRoot: isFileInPnpmRoot(appRootPath, "pnpm-lock.yaml"),
+});
     if ((packageLockExists || shrinkWrapExists) && yarnLockExists) {
         if (overridePackageManager) {
             return overridePackageManager;
```

**Comment by milahu** [comment]
@boldwade please try https://github.com/milahu/patch-package-with-pnpm-support/commit/3545f96852e6f43639998d3b94a9cc49c0c9a529

do you have a lockfile in a parent folder? (or in the same folder as package.json)

**Comment by hcharley** [comment]
This worked for me. Thanks @milahu !

`npx @milahu/patch-package-with-pnpm-support @my-org/my-package`

**Comment by StarpTech** [comment]
Hi, I couldn't find any solution to patch pnpm packages. The solutions above aren't compatible with pnpm's `.pnpm` directory.

**Comment by milahu** [comment]
> The solutions above aren't compatible with pnpm's `.pnpm` directory.

only works for top-level dependencies, as pnpm has deep node_modules
&rarr; add the dependency to package.json

**Comment by StarpTech** [comment]
@milahu thanks. What's missing to integrate your changes into the official repo?

**Comment by milahu** [comment]
> integrate your changes into the official repo?

the owner is gone, so nobody has access*. feel free to maintain a fork ; )

\* github requires the owner's consent for project transfer, which is good

> For account security reasons, we’re unable to alter repository ownership. This policy is in place to protect all account owners from unauthorized takeovers. ([source](https://github.community/t/what-is-github-policy-about-abandoned-repositories/117668/2))

**Comment by gunar** [comment]
We don't need repository ownership - we'd need ownership of the npm package.

**Comment by zkochan** [comment]
pnpm has a [`pnpm patch`](https://pnpm.io/cli/patch) command since v7.4

**Comment by karlhorky** [comment]
## Converter script: `patch-package` patches to pnpm patches

If you're looking to move from `patch-package` to pnpm for patches, here's my quick version of a script to convert from `patch-package` patches to pnpm patches:

- https://github.com/karlhorky/pnpm-tricks#convert-patch-package-patches-to-pnpm-patches

<img width="1437" height="817" alt="Image" src="https://github.com/user-attachments/assets/6daaaf33-c0a9-457d-88b4-afc92b274b62" />

I also asked whether such a converter would be considered to be a part of pnpm in future, as an easier, built-in way to migrate from `patch-package` to pnpm:

- https://github.com/pnpm/pnpm/issues/10087
